from app.graph.state import AgentState
from app.agents.supervisor import run_supervisor
from app.agents.repo_analyzer import run_repo_analyzer
from app.agents.code_localizer import run_code_localizer
from app.agents.root_cause import run_root_cause
from app.agents.fix_generator import run_fix_generator
from app.agents.test_runner import run_test_agent
from app.agents.security_reviewer import run_security_reviewer
from app.services.sandbox_service import sandbox_service
from app.services.github_pr_service import create_pull_request
from app.utils.logger import logger

def node_supervisor(state: AgentState) -> AgentState:
    res = run_supervisor(state)
    state.update(res)
    return state

def node_analyze_repository(state: AgentState) -> AgentState:
    res = run_repo_analyzer(state)
    state.update(res)
    return state

def node_locate_code(state: AgentState) -> AgentState:
    res = run_code_localizer(state)
    state.update(res)
    return state

def node_find_root_cause(state: AgentState) -> AgentState:
    res = run_root_cause(state)
    state.update(res)
    return state

def node_generate_fix(state: AgentState) -> AgentState:
    res = run_fix_generator(state)
    state.update(res)
    return state

def node_run_tests(state: AgentState) -> AgentState:
    res = run_test_agent(state)
    state.update(res)
    return state

def node_security_review(state: AgentState) -> AgentState:
    res = run_security_reviewer(state)
    state.update(res)

    sec_res = state.get("security_results", {})
    if sec_res.get("risk_level") == "HIGH" or sec_res.get("passed") is False:
        state["approval_required"] = True

    return state

def node_human_approval(state: AgentState) -> AgentState:
    logger.info(f"Human Approval Node reached for run {state.get('run_id')}: pausing for review")
    state["current_agent"] = "human_approval"
    state["approval_required"] = True
    state["progress"] = 95
    state["status"] = "NEEDS_APPROVAL"
    return state

async def node_finalize(state: AgentState) -> AgentState:
    """Only reached after a human approves — creates the real branch, commit,
    push, and GitHub pull request."""
    run_id = state["run_id"]
    repository = state.get("repository") or {}
    full_name = repository.get("full_name")
    default_branch = repository.get("default_branch") or "main"
    issue_number = state.get("issue_number")
    root_cause = state.get("root_cause", "")
    diff = state.get("proposed_fix", "")

    branch_name = f"devfix/issue-{issue_number}-{run_id[:8]}"
    commit_message = f"Fix: {state.get('issue_title', '')}"[:72] or f"DevFix AI patch for #{issue_number}"

    logger.info(f"Finalize Node: pushing branch '{branch_name}' for run {run_id}")
    sandbox_service.create_branch_commit_push(run_id, branch_name, commit_message)

    pr_title = f"Fix: {state.get('issue_title') or f'issue #{issue_number}'}"
    pr_body = (
        f"Automated fix generated by DevFix AI for issue #{issue_number}.\n\n"
        f"**Root cause**\n{root_cause}\n\n"
        f"```diff\n{diff[:5000]}\n```"
    )

    pull_request = await create_pull_request(
        github_token=state["github_token"],
        full_name=full_name,
        head_branch=branch_name,
        base_branch=default_branch,
        title=pr_title,
        body=pr_body
    )

    logger.info(f"Finalize Node: opened PR {pull_request.get('url')} for run {run_id}")

    state["current_agent"] = "finalize"
    state["progress"] = 100
    state["status"] = "COMPLETED"
    state["approval_required"] = False
    state["branch_name"] = branch_name
    state["pull_request"] = pull_request
    return state
